#PAPI_INCLUDE = -I/home/vweaver1/research/papi/papi.cvs.perfctr/src
#PAPI_LIB = /home/vweaver1/research/papi/papi.cvs.perfctr/src/libpapi.a

#PAPI_INCLUDE = -I/home/vweaver1/research/papi/papi.git/src
#PAPI_LIB = /home/vweaver1/research/papi/papi.git/src/libpapi.a

#PAPI_INCLUDE = -I/home/vweaver1/research/papi/releases/papi-4.1.3/src
#PAPI_LIB = /home/vweaver1/research/papi/releases/papi-4.1.3/src/libpapi.a

#PAPI_INCLUDE = -I/usr/local/lib
#PAPI_LIB = /usr/local/lib/libpapi.a

PAPI_INCLUDE = -I/usr/local/lib
PAPI_LIB = -lpapi
