#!/bin/sh

export TESTS_QUIET=y

echo
echo "* Checking PAPI predefined events"
./papi/papi_br_cn
./papi/papi_br_ins
./papi/papi_br_ins
./papi/papi_br_msp
./papi/papi_br_ntk
./papi/papi_br_prc
./papi/papi_br_tkn
./papi/papi_br_ucn
./papi/papi_bru_idl
./papi/papi_btac_m
./papi/papi_ca_cln
./papi/papi_ca_inv
./papi/papi_ca_itv
./papi/papi_ca_shr
./papi/papi_csr_fal
./papi/papi_csr_suc
./papi/papi_csr_tot
./papi/papi_dp_ops
./papi/papi_fad_ins
./papi/papi_fdv_ins
./papi/papi_fma_ins
./papi/papi_fml_ins
./papi/papi_fnv_ins
./papi/papi_fp_ins
./papi/papi_fp_ops
./papi/papi_fp_stal
./papi/papi_fpu_idl
./papi/papi_fsq_ins
./papi/papi_ful_ccy
./papi/papi_ful_icy
./papi/papi_fxu_idl
./papi/papi_hw_int
./papi/papi_int_ins
./papi/papi_l1_dca
./papi/papi_l1_dch
./papi/papi_l1_dcm
./papi/papi_l1_dcr
./papi/papi_l1_dcw
./papi/papi_l1_ica
./papi/papi_l1_ich
./papi/papi_l1_icm
./papi/papi_l1_icr
./papi/papi_l1_icw
./papi/papi_l1_ldm
./papi/papi_l1_stm
./papi/papi_l1_tca
./papi/papi_l1_tch
./papi/papi_l1_tcm
./papi/papi_l1_tcr
./papi/papi_l1_tcw
./papi/papi_l2_dca
./papi/papi_l2_dch
./papi/papi_l2_dcm
./papi/papi_l2_dcr
./papi/papi_l2_dcw
./papi/papi_l2_ica
./papi/papi_l2_ich
./papi/papi_l2_icm
./papi/papi_l2_icr
./papi/papi_l2_icw
./papi/papi_l2_ldm
./papi/papi_l2_stm
./papi/papi_l2_tca
./papi/papi_l2_tch
./papi/papi_l2_tcm
./papi/papi_l2_tcr
./papi/papi_l2_tcw
./papi/papi_l3_dca
./papi/papi_l3_dch
./papi/papi_l3_dcm
./papi/papi_l3_dcr
./papi/papi_l3_dcw
./papi/papi_l3_ica
./papi/papi_l3_ich
./papi/papi_l3_icm
./papi/papi_l3_icr
./papi/papi_l3_icw
./papi/papi_l3_ldm
./papi/papi_l3_stm
./papi/papi_l3_tca
./papi/papi_l3_tch
./papi/papi_l3_tcm
./papi/papi_l3_tcr
./papi/papi_l3_tcw
./papi/papi_ld_ins
./papi/papi_lst_ins
./papi/papi_lsu_idl
./papi/papi_mem_rcy
./papi/papi_mem_scy
./papi/papi_mem_wcy
./papi/papi_prf_dm
./papi/papi_res_stl
./papi/papi_sp_ops
./papi/papi_sr_ins
./papi/papi_stl_ccy
./papi/papi_stl_icy
./papi/papi_syc_ins
./papi/papi_tlb_dm
./papi/papi_tlb_im
./papi/papi_tlb_sd
./papi/papi_tlb_tl
./papi/papi_tot_cyc
./papi/papi_tot_iis
./papi/papi_tot_ins
./papi/papi_vec_dp
./papi/papi_vec_ins
./papi/papi_vec_sp
#./papi/papi_bgl_oed
#./papi/papi_bgl_ts_32b
#./papi/papi_bgl_ts_full
#./papi/papi_bgl_tr_dpkt
#./papi/papi_bgl_tr_full

echo
echo "* Checking general PAPI functionality"
./papi/check_mhz_value
./papi/event_create_race
./papi/unregister

echo
echo "* Checking bugs that can silently produce wrong results"
./papi/core2_constraints
./papi/cpufreq_scaling

echo
echo "* Checking perf_event / libpfm4 features"
./papi/nhm_offcore_response
./papi/perfevent_sw_events
./papi/perfevent_generalized_events
echo
