all:
	cd bugs && make
	cd corner_cases && make
	cd error_returns && make
	cd generalized_events && make
	cd ioctl && make
	cd overflow && make
	cd record_sample && make
	cd sysfs && make
	cd validation && make
	cd validation_privileged && make

clean:	
	rm -rf *~
	cd bugs && make clean
	cd corner_cases && make clean
	cd error_returns && make clean
	cd generalized_events && make clean
	cd ioctl && make clean
	cd overflow && make clean
	cd record_sample && make clean
	cd sysfs && make clean
	cd validation && make clean
	cd validation_privileged && make clean
