all:
	cd breakpoints && make
	cd bugs && make
	cd constraints && make
	cd corner_cases && make
	cd error_returns && make
	cd generalized_events && make
	cd ioctl && make
	cd multiplexing && make
	cd overflow && make
	cd rdpmc && make
	cd record_sample && make
	cd sysfs && make
	cd utils && make
	cd validation && make
	cd x86_intel && make

clean:	
	rm -rf *~
	cd breakpoints && make clean
	cd bugs && make clean
	cd constraints && make clean
	cd corner_cases && make clean
	cd error_returns && make clean
	cd generalized_events && make clean
	cd ioctl && make clean
	cd multiplexing && make clean
	cd overflow && make clean
	cd rdpmc && make clean
	cd record_sample && make clean
	cd sysfs && make clean
	cd utils && make clean
	cd validation && make clean
	cd x86_intel && make clean

